FROM mhart/alpine-node:8.12.0

RUN apk update && \
    apk upgrade && \
    apk add git

# Create app directory
RUN mkdir -p /srv/tabula
WORKDIR /srv/tabula

# Install app dependencies
COPY package.json /srv/tabula
COPY yarn.lock /srv/tabula

RUN yarn install

# Bundle app source
COPY . /srv/tabula

RUN yarn build

EXPOSE 3000
CMD [ "yarn", "start" ]
