Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id

  SecurityGroup:
    Type: String

  LoadBalancerSubnets:
    Type: List<AWS::EC2::Subnet::Id>

  LoadBalancerName:
    Type: String

  HostedZoneName:
    Type: String

Resources:

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      Scheme: internal
      Subnets: !Ref LoadBalancerSubnets
      SecurityGroups:
        - !Ref SecurityGroup

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${LoadBalancerName}-Default
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP

  DNSRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: LoadBalancer
    Properties:
      HostedZoneName: !Ref HostedZoneName
      Name: !Join ['', [!Ref LoadBalancerName, ., !Ref HostedZoneName]]
      Type: CNAME
      TTL: 60
      ResourceRecords:
        - !GetAtt LoadBalancer.DNSName

Outputs:

  LoadBalancer:
    Description: A reference to the Application Load Balancer
    Value: !Ref LoadBalancer

  LoadBalancerHost:
    Description: The URL of the ALB
    Value: !GetAtt LoadBalancer.DNSName

  LoadBalancerFullName:
    Description: The LoadBalancerFullName for cloudwatch metrics
    Value: !GetAtt LoadBalancer.LoadBalancerFullName

  Listener:
    Description: A reference to a port 80 listener
    Value: !Ref LoadBalancerListener
