version: '2'

services:
  redis:
    build:
      context: ../tabula/
      dockerfile: Dockerfile.redis

  backend:
    build:
      context: ../varnish
      dockerfile: Dockerfile.test
    command: yarn run test-backend

  varnish:
    ports:
      - "3004:80"
    build:
      context: ../varnish/
      dockerfile: Dockerfile.varnish
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000

  test:
    build:
      context: .
    depends_on:
      - redis
      - varnish
    environment:
      - REDIS_PUB_SUB_HOST=redis
      - VARNISH_HOST=varnish
      - DEBUG=*
    command: yarn test
