version: '2'

services:
  varnish:
    ports:
      - "8081:80"
    build:
      context: .
      dockerfile: Dockerfile.varnish
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=3000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: yarn run test-backend

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: yarn test
    depends_on:
      - varnish
      - backend
    environment:
      - DEBUG=*
