FROM mhart/alpine-node:8.12.0

RUN apk update && \
    apk upgrade && \
    apk add git

ARG NPM_ARGS

# Create app directory
WORKDIR /usr/src/app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

# Bundle app source
COPY . .
